### ISSUE TITLE
Pull Dockerfiles into separate repo

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/aleph#22]
We should probably pull the Dockerfiles for concat into a separate repo, and make them suitable for production use. 

Things needed to run in a production container:
- [ ] data volumes (should have one for statement db, and one for rocks datastore)
- [ ] ntp needs to be running in the container

**Comment by parkan** [comment]
Seems like mapping data volumes to actual devices is a bit tricky, we'd need a helper script that creates the symlinks/mountpoints that we then wrap in data volumes.

**Comment by parkan** [comment]
I wonder if we want a dockerized version as a thing for people to install relatively soon. Probably don't need for "V2" release but soon thereafter would be nice.

**Comment by parkan** [comment]
Do we still want to do this? Possibly related to https://github.com/mediachain/deploy though that pertains mostly to concat
