### ISSUE TITLE
improve cbor performance

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/aleph#27]
node-cbor is pretty slow 😞, about 20x slower than [tinycbor](https://github.com/01org/tinycbor) at converting json to cbor.

Improving this probably means using tinycbor or another native code solution, which could go a few different ways:
- write a command line app to pipe json through and get CBOR maps out the other end
  - don't need to mess with FFI
  - need to figure out how to delimit objects in the output
  - IPLD transform needs to be in native code for tag handling
  - could be used by any language (go, etc)
  - can spawn multiple concurrent processes
- write a C addon or use node-ffi to wrap a native cbor lib
  - FFI is tricky, could potentially crash the node process
  - gives us more flexibility (can expose CBOR tags, etc)
  - no IPC overhead, but blocks the JS thread unless we get fancy with async code
- (crazy option) try to compile tinycbor to webassembly and run node with the `--expose-wasm` flag 😄

**Comment by parkan** [comment]
Turns out you can optimize pure js enough!
