### ISSUE TITLE
Recommended general purpose schemas

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/aleph#54]
For mediachain-first data.

**Comment by denisnazarov** [comment]
If your data is mediachain-first, then presumably it wont have any WKIs at all. What's the best practice here?

**Comment by denisnazarov** [comment]
Def. some good stuff on schema.org: http://schema.org/ImageObject

Can we suggest using schema.org and generating UUIDs for now?

**Comment by parkan** [comment]
I think recommending schema.org as baseline is fine.

For IDs I am not 100% sure UUID is ideal; something like https://github.com/boundary/flake that uses peerIds instead of MACs could be a better choice (though we should think about what information we want to leak)

**Comment by denisnazarov** [comment]
https://github.com/mediachain/aleph/issues/57

**Comment by parkan** [comment]
@yusefnapora this probably falls under documentation scope?

**Comment by yusefnapora** [comment]
Yup, sounds good.

**Comment by parkan** [comment]
@yusefnapora what's the status here?

**Comment by yusefnapora** [comment]
So far I've just got a few paragraphs that amount to "use JSON-LD with schema.org types".  I haven't pushed that section to the docs site yet, but I'm planning to get that done today.

**Comment by parkan** [comment]
@yusefnapora let's try to get this wrapped ASAP, doesn't have to be detailed at this point.

**Comment by yusefnapora** [comment]
@parkan I just pushed an update to the docs site: https://mediachain.github.io/mediachain-docs/publishing/schema-recommendations#using-json-ld

I think it does a decent job of covering the basics, given the current state of support in the code so far.

**Comment by parkan** [comment]
Great, that's more than sufficient 😄
