### ISSUE TITLE
aleph-concat pairing

### ISSUE THREAD

**Issue by parkan** [mediachain/aleph#58]
Configure an aleph to have some notion of an associated concat that it's mated to and uses as the respective datastore. This will be useful for #19, #25, etc

**Comment by parkan** [comment]
@vyzo @yusefnapora thoughts on this? if it sounds reasonable I'll go ahead and implement

**Comment by vyzo** [comment]
Sure, go for it -- it's a reasonable model for repl interaction.

**Comment by denisnazarov** [comment]
will this let us drive a cloud deployed concat w/ a local aleph?

**Comment by parkan** [comment]
@denisnazarov yes

**Comment by vyzo** [comment]
The simplest way to do it is by forwarding the API port using ssh:
```
ssh -N -L 9002:localhost:9002 user@ipaddr
```

**Comment by parkan** [comment]
@vyzo this covers the mcclient case, but I'd like to be able to hook aleph repl up too -- which can use the public libp2p interface

**Comment by parkan** [comment]
you can now manually configure the aleph-concat pairing as `remotePeer` in `~/.mediachain/aleph/config.json` (or just pass --remotePeer), will add configuration commands to the CLI in 1.3
