### ISSUE TITLE
No error if --schemaReference doesn't exist

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/aleph#68]
`mcclient publish` just exits if the hash of the schema doesn't exist without telling you what went wrong.

**Comment by yusefnapora** [comment]
I get this (less than ideal) message:

```
(node:41754) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to retrieve schema with object id QmXciNhn4P6veuojsR6uRGHBu27pAztp5o1rtMkkmsTtUz: Not Found
Error: Unknown Object
```

maybe it's a node version thing though... perhaps the unhandled rejection warning isn't on your version.  I need to be catching that error anyway though, will fix.
