### ISSUE TITLE
No "deps" in publish output

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/aleph#69]
Even though we now have deps, its not in the publish "log" output, just seeing:

```
statement id: 4XTTM9Y6Sso29BhUFWsNwjRbtmQrTz1oYSPfVNFxMkhLyH7iF:1478226868:129023
[ { object: 'QmTXSkbqGr5Rb6dABrzaKK8xKqaBGLfUsXDBcCtR5cwi8n',
    refs: [ '207152' ],
    tags: [] } ]
```

even though there is now a schema hash in the dep.

Also what are tags?

**Comment by yusefnapora** [comment]
Fixed the deps in #71 - good point about the tags; they're for surfacing info from your records that you want to be able to search in a query.  But we don't really support them yet...
