### ISSUE TITLE
[SUMMARY] Aleph core

### ISSUE THREAD

**Issue by parkan** [mediachain/aleph#7]
Core Aleph functionality. Goals: 

- [x] Accept connections with libp2p

~~We accomplish this through two modes of operation, [superpeer] (real aleph node) and [thinclient] (empty client)~~

**Comment by parkan** [comment]
@denisnazarov moved goals here since milestone summary eats formatting. The goals and implementation issues are not quite 1:1, so I'm ok with having these in here separately.

**Comment by denisnazarov** [comment]
@parkan thanks, this is helpful! is directory something super simple like a hard-coded text file?

**Comment by parkan** [comment]
@denisnazarov here, the "directory" is an abstraction with no clear shape yet (probably actually manifest as an SQL table)
