### ISSUE TITLE
make cbor size limit configurable

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/aleph#76]
#75 upped the highWaterMark for the cbor encoder stream to 1MB - we should either make this astronomically high, or make it configurable.  

The highWaterMark is supposed to be used for backpressure, to let the underlying resource catch up... but the way we're feeding the encoder is entirely synchronous and in-memory, so maybe an absurdly large limit is the way to go.

**Comment by parkan** [comment]
Superseded by https://github.com/mediachain/aleph/pull/131
