### ISSUE TITLE
"npm run build-jq" fails when building Aleph

### ISSUE THREAD

**Issue by robertsdotpm** [mediachain/aleph#97]
Hello, I'm trying to build Aleph on version 6.9.1 of Node on Ubuntu 16.04.1 LTS with release 1.2.1 of Aleph but it fails with the follow error:

> aleph@1.2.1 build-jq /usr/lib/node_modules/aleph
> node scripts/build-jq.js

building jq...
err { Error: ./configure --disable-maintainer-mode && make && cp ./jq /usr/lib/node_modules/aleph/node_modules/.bin/jq
Command failed: cp ./jq /usr/lib/node_modules/aleph/node_modules/.bin/jq
cp: cannot create regular file '/usr/lib/node_modules/aleph/node_modules/.bin/jq': Permission denied

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cp ./jq /usr/lib/node_modules/aleph/node_modules/.bin/jq' }

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-jq"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! aleph@1.2.1 build-jq: `node scripts/build-jq.js`
npm ERR! Exit status 1

This also fails as root. Any ideas?

**Comment by yusefnapora** [comment]
Thanks for reporting this; I was just able to reproduce on a 16.04 VM.  I should hopefully have a fix soon and we'll publish a new point release.

**Comment by yusefnapora** [comment]
Hey @robertsdotpm, I just pushed a 1.2.2 release and now I can run `npm install -g aleph` on my ubuntu 16.04 VM.  Hopefully that'll clear it up for you as well.  Thanks again!

**Comment by robertsdotpm** [comment]
Thanks for the fix. I've tested it again and can confirm that it's all working for me :+1:
